### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by Klian** [levrik/mdi-react#10]
Hi,

Thank your for the library!

One question... how can I set the size ?

**Comment by ghufr** [comment]
You can use **width={64}** & **height={64}** or `style={{width: 64, height: 64}}`

but be able to set **size={64}** is more convenient, since material icon have 1:1 aspect ratio

**Comment by levrik** [comment]
@ghufr Thank you for answering. I think adding a `size` prop is a good idea. I will add it with the next mdi update.

**Comment by lordnox** [comment]
In #15 and #12 this property is included

**Comment by levrik** [comment]
The property was added in d5aac537dfcf800a1cdbc24975b4efcdb7766981 but not released yet. I will close this issue as soon as the new version is released.

**Comment by levrik** [comment]
Released in 3.0.0
