### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by brianezequielfiszman** [levrik/mdi-react#11]
How do I change the color of each icon?

**Comment by levrik** [comment]
You can change the color via CSS. Just use the `className` prop to assign a class and set the color as `fill: ...;` inside your CSS.

To change the default color just add the following rule to your CSS:

```css
.mdi-icon {
  fill: ...;
}
```

I'm planning to make this type of common customization easier in a future release so stay tuned.

**Comment by bardleware** [comment]
@brianezequielfiszman you can use any property that an SVG element can use. So you could say
```js
<ExampleIcon fill='#000000' />
```
and the icon would get the fill color you give it.

**Comment by levrik** [comment]
@bardleware Ah, yes. This should also be possible. Completely forgot about that.

**Comment by lordnox** [comment]
In #15 and #12 the property `color` is included

**Comment by levrik** [comment]
The property was added in 544b865a886fd87233e8fe4e0201832bd39286db but not released yet. I will close this issue as soon as the new version is released.

**Comment by levrik** [comment]
Released in 3.0.0
