### ISSUE TITLE
Consider using a font instead of individual svgs?

### ISSUE THREAD

**Issue by RavenHursT** [levrik/mdi-react#14]
Seems like these two issues would be much more simply addressed if this package just utilized an icon-font, that way text CSS props would just be inherited? 
https://github.com/levrik/mdi-react/issues/11
https://github.com/levrik/mdi-react/issues/10

**Comment by levrik** [comment]
I'm not a fan of icon fonts. There are so many reasons why they shouldn't be used anymore.
Both issues can manually be resolved. It's also possible to make SVG icons adapt the text properties.
I want to provide a better API with the next release and maybe I'm also going to add defaults to the icons that they adapt to the text around them 🙂
