### ISSUE TITLE
ES module syntax imports are significantly slower

### ISSUE THREAD

**Issue by martpie** [levrik/mdi-react#20]
Hello :)

I am using Webpack 4, and:

```
import { VolumeHighIcon, VolumeMediumIcon, VolumeLowIcon, VolumeOffIcon } from 'mdi-react';
```

is significantly slower (around 20 seconds?)

than importing icons that way:

```
import VolumeHighIcon from 'mdi-react/VolumeHighIcon';
import VolumeMediumIcon from 'mdi-react/VolumeMediumIcon';
import VolumeLowIcon from 'mdi-react/VolumeLowIcon';
import VolumeOffIcon from 'mdi-react/VolumeOffIcon';
```

The Webpack hint is: 

```
 92% after chunk asset optimization SourceMapDevToolPlugin bundle.js generate SourceMap
```

**Comment by levrik** [comment]
Hey there,
thanks for opening that issue.

Without investigating I would guess that the slow compilation time has to do with the parsing of that huge single icons module. If you import the icons via their direct import path you're only importing a small amount of code which gets processed faster.
The only thing which confuses me here is the hint by Webpack. I have no idea what than one means.

I would suggest to you to use the direct import path for now. I will investigate the other imports as soon as I have time to do so.

**Comment by levrik** [comment]
@KeitIG Could you create an minimal example that reproduces this issue? Thanks!

**Comment by KeitIG** [comment]
Hey!

Yep I will try to do a minimal repo with that problem

**Comment by levrik** [comment]
Awesome, thanks.

**Comment by felixfbecker** [comment]
My guess would be that the tree shaking in webpack only works well with ES6 modules, but react-mdi is only distributed as CommonJS modules. One possible solution would be to add a folder with the ESM versions and add a `module` field to package.json that points to the ESM index.js.

**Comment by levrik** [comment]
@felixfbecker That's plainly wrong. `mdi-react` ships with ES modules since version 3.0.0

**Comment by levrik** [comment]
@felixfbecker Ah. I didn't check if tree shaking is working after merging that PR because I trusted the contributor.
Then I'll have to experiment a bit with different types of builds. Planning that for the next weekend.
@KeitIG I think I just need a general tree shaking setup so you don't have to submit an example repo.

**Comment by levrik** [comment]
I removed ES modules in favor of the single packaged components in 5.0.0
