### ISSUE TITLE
Add support for spin, rotate and flip

### ISSUE THREAD

**Issue by lenzi-erickson** [levrik/mdi-react#28]
I would like to be able to pass in spin, rotate and flip and it automatically have the appropriate styling. Basically adding the functionality of the helper css classes at the bottom of this page: https://cdn.materialdesignicons.com/2.3.54/

`<CarIcon spin={true} />`

`<CarIcon flip="h" />`
`<CarIcon flip="v" />`

`<CarIcon rotate={45} />`
`<CarIcon rotate={180} />`

**Comment by levrik** [comment]
I'm not sure if I want to include that. That would make the individual components more complex and it can be easily achieved by attaching a custom CSS class.

**Comment by levrik** [comment]
Closing since this would just blow up the icons in size. It can be easily achieved by using custom CSS.
