### ISSUE TITLE
Default color 'CurrentColor'

### ISSUE THREAD

**Issue by lenzi-erickson** [levrik/mdi-react#32]
Wouldn't it make more sense if the default color was 'CurrentColor' instead of black? That way it just defaults to the text color unless you pass a specific color.

**Comment by levrik** [comment]
Sadly that's only possible with CSS and would make this library more complex.
There are simple examples how to achieve that in the README though.

**Comment by lenzi-erickson** [comment]
I guess I don't see the need to add css. Just change
`{ color = '#000', size = 24, children, ...props }`
to
`{ color = 'currentColor, size = 24, children, ...props }`

That's what I was hoping for. I haven't tested it, but I think that should do the trick.

**Comment by lenzi-erickson** [comment]
And you can do it with css like this
```
:global {
  .mdi-icon {
    fill: currentColor;
  }
}
```
but then it overrides the color prop and you can no longer pass prop as a color. I was hoping to be able to have it default to the currentColor but still be able to pass a color prop to the icon.

**Comment by levrik** [comment]
As I said, it's only possible with CSS.
The `color` prop just passes it's value to the `fill` prop of the SVG path. `currentColor` isn't supported there.
The README is all I can do without adding CSS stuff to the library itself.

**Comment by levrik** [comment]
Released in 4.0.0
