### ISSUE TITLE
Generic icon element

### ISSUE THREAD

**Issue by AustinErck** [levrik/mdi-react#36]
Add a generic `Icon` component that takes a prop called `icon` which allows us to dynamically change the icon based on a string.

**Comment by levrik** [comment]
`mdi-react` uses inline SVG which makes it kinda difficult or even impossible to create a generic `Icon` component. For that an icon font or similar would be necessary.
I will close this for now.
But I'm curious: What's your use case you need a generic `Icon` component for?

**Comment by AustinErck** [comment]
I wanted to create a custom button component with a couple things wrapped around a button. Currently I'm using a switch statement to select (from a small number of icons I need) the icon that appears in the button.

**Comment by levrik** [comment]
I would suggest you to add an icon prop which accepts a component instead of a string.
Quick example: https://codesandbox.io/s/rk8xnrnyn
