### ISSUE TITLE
DeleteOutlineIcon is not included

### ISSUE THREAD

**Issue by jonotron** [levrik/mdi-react#38]
I can get lots of the other `Delete` icons, but not the outline one. There are also lots of other `xOutline` icons.

Must have been forgotten?

**Comment by jonotron** [comment]
Hmm... I see this is an upstream issue, https://github.com/Templarian/MaterialDesign-SVG/tree/master/svg also does not contain `DeleteOutline`

**Comment by levrik** [comment]
That's fixed in the 4.1.0 release 🎉
