### ISSUE TITLE
Use react.memo for the icons to prevent re-renders?

### ISSUE THREAD

**Issue by merisbahti** [levrik/mdi-react#52]
Have you considered adding React.memo to the icons to prevent unneccesary re-renders? As of right now react devtools always show icons re-rendering even though the dom does not change.

**Comment by levrik** [comment]
That's a good idea.
`React.memo` wasn't available when I started the library.
Can you issue a PR with the change?
I would prefer it to be backwards-compatible to support older versions of React as well.

**Comment by merisbahti** [comment]
Done, thanks for the merge. Do you have any timeline for release? Thanks.

**Comment by levrik** [comment]
Release in `5.4.0`. Thanks!

**Comment by smeijer** [comment]
I don't think the overhead of memo, is worth it. Which case would rerender an icon unwillingly? And why wouldn't it be possible to catch those exceptions in the parent component? 

Most applications have a lot of icons, with mostly the simple options like size and color, which are always equal by reference. 

I would advise reading this post from Kent C. Dodds, and ask to reconsider the usage of react.memo. 

https://kentcdodds.com/blog/usememo-and-usecallback

**Comment by merisbahti** [comment]
We’re not using useMemo, we’re using memo. It’s a completely different
thing. It’s not a hook. Imagine it’s like implementing
shouldComponentUpdate for functional components.

**Comment by smeijer** [comment]
I'm aware it's a different thing, and I know what it does. But the same logic applies. 

Memo adds overhead, and I'm not sure if it's worth the costs at the end of the tree. The svg node will never have any children. So this is the last component to optimize. 

If an icon is being rerendered, it should be prevented by its parent. Now we add overhead to every icon on the page, because there might be one  component that's being updating its icons unesasarily.

The real question is, why does the icons parent trigger the rerender?

**Comment by merisbahti** [comment]
The overhead it adds is an implicit ”shouldComponentUpdate” method that
looks like this: `() => false`. Note that for React.memo it’s more like an
”isEqual” method so the predicate is reversed.

**Comment by merisbahti** [comment]
Right, so I'm back and I've created a simple app: https://github.com/merisbahti/perf-test-example.

It uses react-mdi version 5.3.0, since that's before `React.memo` was added, and the code basically looks like this:
```
import React from 'react'
import AlertIcon from 'mdi-react/AlertIcon';
const MemoizedIcon = React.memo(AlertIcon)

const style = {
  display: 'flex',
  flexDirection: 'column',
  width: '200px'
}

const App = () => {
  const [state, setState] = React.useState(0)
  const [memoized, setMemoized] = React.useState(false)

  const inc = React.useCallback(() => void setState((state) => state + 1), [])
  const toggleMemo = React.useCallback(() => void setMemoized(state => !state), [])

  return (
    <div style={style}>
      <button onClick={inc}>update {state}</button>
      <button onClick={toggleMemo}>{memoized ? 'using memoized' : 'not memoized'}</button>
      <div>
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
        { memoized ? <MemoizedIcon />: <AlertIcon />}
      </div>
    </div>
  )
}
export default App
```

So it's an simple app. We have one button to trigger some kind of re-render in the App component, one button to toggle between using memoized and not-memoized icons, and 10 icons of the chosen kind.

The question was, does this add overhead? Well, let's use reacts performance tools to check this!

First image, 10 clicks on update button without memoization:
<img width="668" alt="not-memoized-ten-icons-ten-updates" src="https://user-images.githubusercontent.com/2946728/65371419-c797d400-dc63-11e9-8cdd-9b21d4067a26.png">

This looks normal, that's how react works.

Second image, 10 clicks on update button *with* memoization:
<img width="667" alt="memoized-ten-icons-ten-updates" src="https://user-images.githubusercontent.com/2946728/65371436-ebf3b080-dc63-11e9-87d2-25fd173ebdab.png">

What's going on here? The icons are not updating even though a parent component updated? This is because `React.useMemo` adds an implicit "areEqual" function to the component, this implicit areEqual method that shallowly compares props, and since no props coming into the icon components have changed (they take none), they do not update. This is probably the overhead you are talking about.
See the docs for `React.memo` here: https://reactjs.org/docs/react-api.html#reactmemo

But are the geniuses behind React simply fooling us here with the react devtools that they control? Using the built in performance profiler of chrome, and running the same experiment (10 state updates, 10 icons, both memo and not-memo):

Not memo: 

<img width="661" alt="perf-tab-not-memoized" src="https://user-images.githubusercontent.com/2946728/65371509-71776080-dc64-11e9-9c48-6cfa05686915.png">

With memo:
<img width="659" alt="perf-tab-memoized" src="https://user-images.githubusercontent.com/2946728/65371513-76d4ab00-dc64-11e9-8b08-49a8d5c4ae8a.png">

So the *scripting*-, *rendering*- and *system*-time is higher for not-memoized components in this case.

So yes, `memo` adds code and adds the overhead of shallowly comparing props - but this overhead is smaller than the overhead of re-rendering the components.

**Comment by MaSsoumeh** [comment]
React saves all memoized components and values to memory. So with memoization, we trade memory space for time. Although the memory overhead in memoization is minimal but may not be worth the cost and still it seems more logical to memoize a component when necessary.
