### ISSUE TITLE
Re-export all modules from an index.js file

### ISSUE THREAD

**Issue by merisbahti** [levrik/mdi-react#55]
Hey, is there any specific reason we dont export all icons from an `index.js`-file?

I've created a fork which exports the icons using the `export {default as Icon} from './Icon'`-syntax. A great benefit from this would be easier import-syntax. Additionally, it enables bundlephobia analysis of this package (see https://bundlephobia.com/result?p=mdi-react).

Please see my pull-request:
https://github.com/levrik/mdi-react/pull/54

**Comment by levrik** [comment]
That feature was removed in `5.0.0`, see https://github.com/levrik/mdi-react/commit/07ec6a17f10c5ec410736e57e6187287e24a32c1

**Comment by masbaehr** [comment]
If some one else stumbles across this i suggest to do the following (at least i cannot see any drawback yet)

One file to export all icons you need in your project. e.g named MdiIcons.js
```javascript
export {default as AccountCardDetails} from 'mdi-react/AccountCardDetailsIcon';
export {default as AccountGroup} from 'mdi-react/AccountGroupIcon';
export {default as AccountSupervisor} from 'mdi-react/AccountSupervisorIcon';
```

```javascript
import * as MdiIcons from './utils/MdiIcons';
//Usage:
<MdiIcons.AccountGroup/>
```
This will avoid a lot of code duplication, and makes it possible to easily include icons without waiting for VSCode to index everything (intelli sense seems slow)
