### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function but got: object

### ISSUE THREAD

**Issue by ArtemBernatskyy** [levrik/mdi-react#56]
When upgrading to latest version I've got this errors.
When I remove mdi icons from component it goes away.

From `4.4.0` -> `5.4.0`

**Comment by sawady** [comment]
Same problem

**Comment by ArtemBernatskyy** [comment]
@sawady it is fixed via this https://stackoverflow.com/a/53061048/5751147
You need to have the same version of `react` and `react-dom`

**Comment by levrik** [comment]
@ArtemBernatskyy @sawady `react` and `react-dom` should always be the same version. Please keep that in mind!
