### ISSUE TITLE
Element type is invalid: expected a string

### ISSUE THREAD

**Issue by ahmadkam72** [levrik/mdi-react#58]
Hi every guys 
when I use this library and import icon and use in my render method, I faced with this error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`
Can anyone help me to fix this?
Thank you.

**Comment by levrik** [comment]
Can you post your code, please?

**Comment by ahmadkam72** [comment]
Its wired but when I test it again now,
it works with no error
`
import AccountOutlineIcon from 'mdi-react/AccountOutlineIcon';
import CashIcon from 'mdi-react/CashIcon';

class NewGoodForm extends PureComponent {
  static contextTypes = {
    router: PropTypes.objectOf(PropTypes.object),
  }

  constructor() {
    super();
    this.handleSubmit = this.handleSubmit.bind(this);
    this.handleInputChange = this.handleInputChange.bind(this);
    this.isFormInvalid = this.isFormInvalid.bind(this);
  }

  

  }

  render() {
    return (
      <form className="form" onSubmit={this.handleSubmit}>
        <Container>

          <Row>

            <Col md={6}>
              <FormItem
                label="نام کالا"
                hasFeedback
                validateStatus={nameValidateStatus}
                help={nameErrMsg}
              >
                <div className="form__form-group-icon">
                  <AccountOutlineIcon />
                </div>
                <input
                  name="name"
                  autoComplete="off"
                  type="text"
                  className="persianText"
                  placeholder="نام کالا"
                  value={nameValue}
                  onChange={event => this.handleInputChange(event, this.validateName)}
                />
              </FormItem>
            </Col>

            <Col md={6}>
              <FormItem
                label="price"
                hasFeedback
                validateStatus={priceValidateStatus}
                help={priceErrMsg}
              >
                <div className="form__form-group-icon">
                  <CashIcon />
                </div>
                <input
                  name="price"
                  autoComplete="off"
                  type="number"
                  className="persianText"
                  placeholder="price"
                  value={priceValue}
                  onChange={event => this.handleInputChange(event, this.validatePrice)}
                />
              </FormItem>
            </Col>

          </Row>

          <Row className="justify-content-md-center">
            <Col md={4} className="col">
              <button
                type="submit"
                className="btn btn-primary account__btn account__btn--small"
                disabled={this.isFormInvalid()}
              >Add
              </button>
              <Link className="btn btn-outline-primary account__btn account__btn--small" to="/pages/one">back</Link>
            </Col>
          </Row>

        </Container>


      </form>
    );
  }
}

export default NewGoodForm;
`

**Comment by levrik** [comment]
If it works, I'll close this issue.
