### ISSUE TITLE
Changelog is not friendly for developers deciding whether to upgrade

### ISSUE THREAD

**Issue by Slapbox** [levrik/mdi-react#68]
It's painstaking to determine what's changed since the version you're currently using.  It also includes tons of unreleased changes. An overview of what's changed between minor and major versions is extremely important in my view. We can't upgrade because we don't have time to figure out what's changed.

**Comment by levrik** [comment]
As mentioned in https://github.com/levrik/mdi-react/blob/master/CHANGELOG.md, only changes to this library itself are documented there. For changes on the actual icons, please refer to the changelog of `mdi` found [here](https://materialdesignicons.com/history).
You can find the version of `mdi` included in a release also on the changelog here.
