### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Falieson** [levrik/mdi-react#7]
I've tried running dts-gen to resolve `cannot find module mdi-react` and just `declare module "mdi-react'";` neither of which works. dts-gen says it `couldn't load module "mdi-react"`

Thank you for your help...

**Comment by levrik** [comment]
@Falieson I don't use Typescript so I cannot help there. Sorry. Feel free to submit a PR to add typescript support. There was already some work done in #2.

**Comment by lordnox** [comment]
Hi @levrik 
If I create a pull request to ship a typings.d.ts you would merge it?
Because you declined #2 
I would be happy to create one

**Comment by levrik** [comment]
@lordnox Yes, please create one. I know TypeScript a bit better now so I can review it 🙂

**Comment by lordnox** [comment]
Btw. I used this script to see the typings in my editor:
```
import * as React from 'react'

import Comp from 'mdi-react/AccountBoxOutlineIcon'
import { AccountBoxIcon } from 'mdi-react'

const x = <AccountBoxIcon width />

const y = <Comp width />

console.log(x, y)
```

Both `width` fields were supposed to be `number`. The message was `true` is not assignable to type `number`.

**Comment by levrik** [comment]
Typings were added in 46e7c3bd65f483758144c90f0f608c30737550f2 but not released yet. I will close this issue as soon as the new version is released.

**Comment by levrik** [comment]
Released in 3.0.0

**Comment by levrik** [comment]
@MrSchnitzel I saw that you've added TypeScript support in your fork. Can you try the latest 3.x? `mdi-react` comes with TS typings since 3.0.0 🙂

**Comment by MrSchnitzel** [comment]
Yhea I did, or at least i tried but it was only kind of a workaround.
Cool that u integrated it; nice to hear!
Thanks for the Update!
