### ISSUE TITLE
mdi-text-box icons are missing

### ISSUE THREAD

**Issue by masbaehr** [levrik/mdi-react#75]
Hi, just updated to the shiny new version, but some things are not right now:

https://github.com/Templarian/MaterialDesign/issues/4901

For example all codepoints have been changed and some icons for example "TextBoxIcon" now produce the wrong icon according to 

http://materialdesignicons.com/cdn/5.0.45/

**Comment by levrik** [comment]
I don't fully get what the issue is here. Does `TextBoxIcon` differ from what you can see in the link you've posted?

**Comment by masbaehr** [comment]
Hm i expected it to be like this: 
![image](https://user-images.githubusercontent.com/38694044/76197646-d449bd80-61ec-11ea-85e6-f2644a3116aa.png) 

But it seems that the actual error/confusion might not be in mdi-react but in materialdesignicons. Sorry for the trouble caused. Just to understand: When they change something in the codepoint, for mdi-react this does not matter? Then the issue can actually be closed

**Comment by masbaehr** [comment]
Strange thing i noted: 
![image](https://user-images.githubusercontent.com/38694044/76197855-373b5480-61ed-11ea-9202-b0b6381a693b.png)

**Comment by levrik** [comment]
The codepoints are used with the icon font. `mdi-react` exposes the SVG icons.
The `mdi-text-box` icon should be converted to `TextBoxIcon` and `mdi-textbox` to `TextboxIcon`.
Which doesn't really work for case insensitive file systems. But also from materialdesignicons' side this seems quite confusing. Maybe open an issue over at their repo. If they don't want to change this I'll think about a different naming conversion so I'll keep the issue open for now.

**Comment by masbaehr** [comment]
Maybe for providing a temporary fix to this you could just make an exception for this one. An ugly but working solution is still better than no solution :) As far as i have seen, this is the ONLY case with this name clash

For example:
TextboxInputIcon 

Probably at materialdesignicon they just think about css-classes when deciding for a name

**Comment by Templarian** [comment]
@levrik You can close this by the way. This was fixed upstream in 5.1+ months ago. `form-textbox` is the prefix. This was to prevent enum issues with `TEXTBOX` in other third party tooling. 👍 

We also have added checks to prevent name collisions in the future.

**Comment by levrik** [comment]
@masbaehr Can you confirm this to be fixed in newer versions?

**Comment by masbaehr** [comment]
I think it is fine now thus im closing the issue. Although i migrated to mdi-material-ui in the meantime as it supports tree-shaking
