### ISSUE TITLE
incorrect icon for ImageIcon

### ISSUE THREAD

**Issue by jonotron** [levrik/mdi-react#8]
when using `ImageIcon` I am expecting to see 

![material design icons 2017-11-07 10-54-10](https://user-images.githubusercontent.com/349600/32511873-006b845e-c3aa-11e7-8f3e-e8545dd78756.png)

But instead I get:

![storybook 2017-11-07 10-54-36](https://user-images.githubusercontent.com/349600/32511906-13f43200-c3aa-11e7-9f69-31137a8ff7f4.png)

I've cloned the repository and run `npm run build` and it does seem to create the correct SVG for `ImageIcon` so I think the published package is somehow out of date.

Could this be published to get a correct icon? Thanks!

**Comment by levrik** [comment]
Indeed.. there is some difference between a freshly built version and version published on npm.
I will investigate why this happened and publish a fixed version very soon.

**Comment by jonotron** [comment]
Great! Thanks for looking into it, and thanks for this package.

**Comment by levrik** [comment]
Basically it's broken on `master` of `mdi` (https://github.com/Templarian/MaterialDesign/blob/89421efe9b30b3377f9203c8c8438381148a6df2/icons/svg/image.svg).
This repository was used to publish the latest version. There's a new repo now which contains a fixed version
(https://github.com/Templarian/MaterialDesign-SVG/blob/master/svg/image.svg). The `build` script is already using that but there was no release of `mdi` yet.
I will publish a hotfix for `2.0.46` created out of the new repo asap.

**Comment by jonotron** [comment]
I noticed that you are using version numbering that matches `mdi`/`mdi-svg`. Hopefully that doesn't cause problems for the npm publish.

**Comment by levrik** [comment]
Yes.. actually that's a blocker for publishing a new version at the moment. I didn't expect to get into the situation where I need to publish a new version apart from a new `mdi` release.
I just published the hotfix as `2.0.46-hotfix.0` for now. You need to put this exact version into your `package.json` since actually it's a pre-release in the semver world.
Need to rethink my versioning but wanted to get out a fixed version for you 🙂

**Comment by jonotron** [comment]
Works great! Much thanks for the splendidly quick response
