### ISSUE TITLE
How to set title attribute on an icon?

### ISSUE THREAD

**Issue by inimist** [levrik/mdi-react#98]
Is it possible to set "title" attribute on icon to show tooltip. Is there a list of attributes an icon component supports?

**Comment by levrik** [comment]
All icon components support all props a standard SVG element supports. This also includes `title`.

**Comment by acooo1** [comment]
@levrik `title` is not a valid `<svg>` attribute. It is not supported by browser and will then not display a tooltip. Setting this prop should instead pass a `<title>` element as a child of the `<svg>`.

**Comment by levrik** [comment]
@acooo1 I wasn't aware of this. Could you file a new issue as that one here is specifically asking about the `title` attribute.

**Comment by acooo1** [comment]
> of this. Could you file a new issue as that one here is
Issue opened
